### ISSUE TITLE
About object detection experiment in your work

### ISSUE THREAD

**Issue by EinesTages** [huanranchen/AdversarialAttacks#4]
I am following your work and will soon cite it. Could you please tell me more details about how you perform this experiments ?  If possible, I would greatly appreciate it. My email is 3275900045@qq.com.

**Comment by huanranchen** [comment]
Thank you for following my work.

The object detection part is based on our previous CVPR paper "T-SEA: Transfer-based Self-Ensemble Attack on Object Detection". This paper provide a code framework for attacking object detectors, and continuously update during the past two years. (https://github.com/VDIGPKU/T-SEA).


Since this repo is keep updating, I only release the Algorithm part of object detection. (https://github.com/huanranchen/CommonWeaknessDetection). T-SEA repo already gives instructions on how to add new attackers into the T-SEA framework.
